snagflash: fastboot: correct (again) offset computations for sparse files
As reported by #85, flashing a wic image generated by Yocto using
fastboot-uboot mode trigger an error when sending the last image chunk
to the target:

  ValueError: Truncated flash, only 82944 bytes were flashed instead of 86016 bytes

The same issue is reproduced on another platform (SK-TDA4VM).

  [INFO] Flashing to MMC device...
  [DEBUG] setting MMC device to 1
  [DEBUG] fastboot OKAY
  [DEBUG] range start 0x88100000 read size 0x2000
  [DEBUG] send size 0x2000 dst offset 0x88100000
  [DEBUG] fastboot DATA length: 8192
  [INFO] fastboot OKAY
  [DEBUG] fastboot OKAY
  [INFO] flashed 8192/8192 bytes
  [INFO] Flashing sparse range 12/13

  [INFO] Flashing to MMC device...
  [DEBUG] setting MMC device to 1
  [DEBUG] fastboot OKAY
  [DEBUG] range start 0x936e0000 read size 0x1c000
  [DEBUG] send size 0x1b800 dst offset 0x936e0000  <<< here we should have "read size" == "send size"
  [DEBUG] fastboot DATA length: 112640
  [INFO] fastboot OKAY
  [DEBUG] fastboot OKAY
  [INFO] flashed 112640/114688 bytes

  [DEBUG] range start 0x936fb800 read size 0x800

  ValueError: Truncated flash, only 112640 bytes were flashed instead of 114688 bytes

0x936fb800 is actually the size of the wic file (2473572352).
This value is verified by the ImageSize value in .bmap file.

  <!-- Image size in bytes: 2.3 GiB -->
  <ImageSize> 2473572352 </ImageSize>

So it means that flash_range() reached the end of the file prematurely:

    blob = file.read(read_size)
    bytes_read = len(blob)

    if bytes_read == 0:
        break

That's why "read size" != "send size" in the Snagflash debug log.

Removing the bmap file allows to workaround this issue.

This bug was probably introduced/uncovered in Snagboot 2.6 by
when "flashing with unspecified file sizes" feature was added.

The first ranges in .bmap are:

  <Range 0-2 </Range>
  <Range 256-5425 </Range>
  <Range 33024-33316 </Range>

It turn out that the image file chunk reading (flash_range()) is off by
one block.

  [DEBUG] range start 0x0 read size 0x3000          <<< 12288 (3x4096) : 0-2 Range
  [DEBUG] send size 0x3000 dst offset 0x0
  [DEBUG] fastboot DATA length: 12288
  [INFO] flashed 12288/12288 bytes
  [INFO] Flashing sparse range 1/13

  [DEBUG] range start 0x100000 read size 0x1432000  <<< 21176320 (5170x4096) : 5169 <= 256-5425
  [DEBUG] send size 0x1432000 dst offset 0x100000
  [DEBUG] fastboot DATA length: 21176320
  [INFO] flashed 21176320/21176320 bytes
  [INFO] Flashing sparse range 2/13

  [DEBUG] range start 0x8100000 read size 0x125000  <<< 1200128 (293x4096) : 292 <= 33024-33316
  [DEBUG] send size 0x125000 dst offset 0x8100000
  [DEBUG] fastboot DATA length: 1200128
  [INFO] flashed 1200128/1200128 bytes
  [INFO] Flashing sparse range 3/13

Fix range_offset computations for sparse files.

Fixes: 2801abb ("snagflash: fastboot: support bmap sparse flashing")
Fixes #85

Signed-off-by: Romain Naour <romain.naour@smile.fr>